SAEZ, ELJENZAL HOPER U.

2ECE - C

DIVISION BY 3 PROBLEM

In [10]:
import numpy as np

# creating a 10x10 ndarray na may squares ng first 100 positive integers
X = np.arange(1, 101).reshape(10, 10) ** 2

# find kung anong elements yung divisible by 3
div_by_3 = X[X % 3 == 0]

# saving the result
np.save('div_by_3.npy', div_by_3)

# print the results
print("Original Array:\n", X)
print("Elements Divisible by 3:\n", div_by_3)

Original Array:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
Elements Divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
