SAEZ, ELJENZAL HOPER U.

2ECE - C

NORMALIZATION PROBLEM

In [21]:
import numpy as np

# creating a random 5x5 ndarray
X = np.random.rand(5, 5)

# calculate the mean and standard deviation
mean = X.mean()
std_dev = X.std()

# normalize the array using the given formula
X_normalized = (X - mean) / std_dev

# save the normalized array to a file
np.save('X_normalized.npy', X_normalized)

# print the results
print("Original Array:\n", X)
print("Normalized Array:\n", X_normalized)

Original Array:
 [[0.37751438 0.4417757  0.63063672 0.60842442 0.97947423]
 [0.98368203 0.68235031 0.4061651  0.55844523 0.33358684]
 [0.63741737 0.09368735 0.96943388 0.56502973 0.4728166 ]
 [0.53936713 0.42864231 0.8157734  0.76703774 0.42130252]
 [0.49592956 0.63767762 0.51131936 0.28629485 0.01059552]]
Normalized Array:
 [[-0.70560771 -0.43676467  0.35335238  0.26042522  1.81274553]
 [ 1.83034922  0.56970084 -0.58574484  0.05133279 -0.88938254]
 [ 0.38171984 -1.89302366  1.77074081  0.07887965 -0.30690227]
 [-0.02848214 -0.49170942  1.12788835  0.92399834 -0.52241607]
 [-0.21020715  0.38280864 -0.14582253 -1.08723281 -2.24064581]]
